# Note 1:
#   It is highly recommended to perform "sudo netplan try" before the actual application.
#
# Note 2:
#   Note that previous changes sometimes remain even if new ones are applied.
#
# Note 3:
#   Sometimes "sudo netplan try" doesn't revert changes for some reason,
#   but they should be reverted if you reboot the system because the Git diff is restored
#   when the system starts up.

network:
  version: 2
  renderer: networkd
  # https://cosmoz.jp/usage/netconf.html (ja)
  ethernets:
    # An original LAN port connected to WAN
    eth0:
      dhcp4: true
      optional: true
      dhcp-identifier: mac
    # An incorporated Wi-Fi interface, which works as an access point managed by hostapd
    wlan0:
      dhcp4: false
      optional: true
      addresses:
        - 192.168.82.1/24
    # An adapter LAN port connected to the other Wi-Fi router
    eth1:
      dhcp4: false
      optional: true
      addresses:
        - 192.168.80.1/24
