# It is highly recommended to perform "sudo netplan try" before the actual application.
# Note that previous changes sometimes remain even if new ones are applied.

network:
  version: 2
  renderer: networkd
  ethernets:
    # https://cosmoz.jp/usage/netconf.html (ja)
    eth1:
      dhcp4: yes
      # An IPv6 address may be assigned through router advertisements, even though DHCPv6 is disabled.
      dhcp6: no
      dhcp-identifier: mac
      optional: true
    eth0:
      dhcp4: no
      dhcp6: false
      accept-ra: false
      link-local: []
      addresses:
        - 192.168.82.1/24
        - fd00:0:0:3::1/64
      routes:
        - to: 192.168.82.0/24
          via: 192.168.82.1
          table: 102
      routing-policy:
        - from: 192.168.82.0/24
          table: 102
      nameservers:
        addresses: [192.168.82.1]
      ipv6-privacy: true
