network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      dhcp4: yes
      addresses:
        - 192.168.150.2/24
      routes:
        - to: default
          via: 192.168.150.1
        - to: 192.168.150.0/24
          via: 192.168.150.1
          table: 101
      routing-policy:
        - from: 192.168.150.0/24
          table: 101
      nameservers:
        addresses: [1.1.1.1]
      ipv6-privacy: true
    eth0:
      dhcp4: no
      addresses:
        - 192.168.82.1/24
        - fd00:0:0:3::1/64
      routes:
        - to: 192.168.82.0/24
          via: 192.168.82.1
          table: 102
      routing-policy:
        - from: 192.168.82.0/24
          table: 102
      nameservers:
        addresses: [1.1.1.1]
      ipv6-privacy: true
